on:
  push:
    branches:
      - main

name: 🚀 Deploy Next.js test Website on Push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: 🔨 Build Project
        run: |
          npm install --legacy-peer-deps
          npm run build
        working-directory: front_end

      - name: 📂 Install lftp
        run: sudo apt-get install lftp -y

      - name: Delete Previous .next Folder
        run: |
          echo "Checking if .next folder exists..."
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; ls test_app/; bye" ftp://ftp.kc-garments.com | grep '.next' || echo ".next folder does not exist."

          echo "Deleting previous .next folder..."
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; rm -rf test_app/.next; bye" ftp://ftp.kc-garments.com || exit 1

          echo "Verifying deletion..."
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; ls test_app/; bye" ftp://ftp.kc-garments.com || exit 1

      - name: 📂 Sync Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.kc-garments.com
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: front_end/build/
          server-dir: test_app/
          exclude: |
            **/node_modules/**
            package-lock.json
            .env
            **/src/**
            .gitignore
