on:
  push:
    branches:
      - main

name: 🚀 Deploy Next.js test Website on Push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: windows-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

       - name: 🔨 Build Project
        run: |
          npm install --legacy-peer-deps
          npm run build
          .\nextjs-standalone-deployer.exe
        working-directory: front_end

      - name: 📂 Sync Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.kc-garments.com
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: front_end/build/
          server-dir: test_app/
          exclude: |
            **/node_modules/**
            package-lock.json
            .env
            **/src/**
            .gitignore
